server:
  port: 8090

spring:
  application:
    name: flux-cache-order

redis:
  host: 127.0.0.1
  port: 6379
  password:

flux:
  cache:
    namespace: flux-cache-order
    defaultCacheLevel: FirstCacheable
    asyncMonitorEnable: true
    cacheMonitorEnable: true
    warmUpEnable: true
    warmUpDelaySeconds: 5

logging:
  level:
    com.fluxcache.example: DEBUG
