server:
  port: 8090


spring:
  application:
    name: flux-cache

redis:
  host: 127.0.0.1
  port: 6379
  password: 123456

flux:
  cache:
    defaultCacheLevel: FirstCacheable
    asyncMonitorEnable: true
    cacheMonitorEnable: true
    #    prefix: /weihubeats

logging:
  level:
    com:
      fluxcache:
      example: DEBUG